<?php

$title = $this->translate('Reset Password');
$this->headMeta()->appendName('keywords', 'Reset, Alter, Password');
$this->headMeta()->appendName('description', 'Reset my account password');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('reset', [], true));
$form->prepare();

?>

<div class="row justify-content-center">
    <div class="col-sm-10 col-md-8 col-lg-6 shadow-sm">

        <h1 class="h2 text-center mb-3">
            <?= $this->translate('Reset Password'); ?>
        </h1>

        <?= $this->form()->openTag($form); ?>

        <div class="mb-3">
            <?= $this->formLabel($form->get('newPassword')); ?>
            <?= $this->formPassword($form->get('newPassword')); ?>
            <div class="text-danger fw-bold">
                <?= $this->formElementErrors($form->get('newPassword')); ?>
            </div>
        </div>

        <div class="mb-3">
            <?= $this->formLabel($form->get('confirmNewPassword')); ?>
            <?= $this->formPassword($form->get('confirmNewPassword')); ?>
            <div class="text-danger fw-bold">
                <?= $this->formElementErrors($form->get('confirmNewPassword')); ?>
            </div>
        </div>

        <div class="mb-3">
            <?= $this->formHidden($form->get('csrf')); ?>
            <div class="text-danger fw-bold">
                <?= $this->formElementErrors($form->get('csrf')); ?>
            </div>
            <?= $this->formSubmit($form->get('resetPassword')); ?>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
