<nav class="d-flex justify-content-center pt-2" aria-label="Page navigation">
    <ul class="pagination">
        <?php if (isset($this->previous)): ?>
        <li class="page-item">
            <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->previous]]); ?>" class="page-link">
                Previous
            </a>
        </li>
        <?php else: ?>
        <li class="disabled page-item">
            <a href="#" class="page-link">«</a>
        </li>    
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page !== $this->current): ?>
            <li class="page-item">
                <a href="<?= $this->url($this->route, [], ['query' => ['page' => $page]]); ?>" class="page-link" aria-current="page">
                    <?= $page; ?>
                </a>
            </li>
            <?php else: ?>
            <li class="page-item active">
                <a href="#" class="page-link"><?= $page; ?></a>
            </li>        
            <?php endif; ?>    
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
        <li class="page-item">
            <a href="<?= $this->url($this->route, [], ['query' => ['page' => $this->next]]); ?>" class="page-link">Next</a>
        </li>
        <?php else: ?>
        <li class="disabled page-item">
            <a href="#" class="page-link">»</a>
        </li>
        <?php endif; ?>
    </ul>
</nav>
