<?php


$title = $this->translate('Login');
$this->headMeta()->appendName('keywords', 'Login, Authenticate, Sign in');
$this->headMeta()->appendName('description', 'Login to your account');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('login'));
$form->prepare();

?>

<div class="row justify-content-center">
    <div class="col-sm-10 col-md-8 col-lg-5 shadow-sm">

        <h1 class="h2 text-center mb-3">
            <?= $this->translate('Member Login'); ?>
        </h1>

        <?= $this->form()->openTag($form); ?>

        <p class="mb-3">
            <?= sprintf($this->translate('Don\'t have an account yet? %sSign up%s'), '<a href="'.$this->url('signup').'">', '</a>'); ?>
        </p>

        <div class="mb-3">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formEmail($form->get('email')); ?>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>
        </div>

        <div class="mb-3">
            <?= $this->formLabel($form->get('password')); ?>
            <div class="float-end">
                <?= sprintf($this->translate('%sForgot Password?%s'), '<a href="'.$this->url('forgot').'">', '</a>'); ?>
            </div>
            <?= $this->formPassword($form->get('password')); ?>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('password')); ?>
            </div>
        </div>

        <div class="form-check mb-3">
            <?= $this->formCheckbox($form->get('recall')); ?>
            <?= $this->formLabel($form->get('recall')); ?>
        </div>

        <div class="mb-3">
            <?= $this->formHidden($form->get('returnUrl')); ?>
            <?= $this->formHidden($form->get('loginCsrf')); ?>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('loginCsrf')); ?>
            </div>
            <?= $this->formSubmit($form->get('accountLogin')); ?>
        </div>

        <?= $this->form()->closeTag(); ?>

    </div>
</div>