<?php

$title = $this->translate('Join');
$this->headMeta()->appendName('keywords', 'Join, Sign up, Create Account');
$this->headMeta()->appendName('description', 'Create a new user account');
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('signup'));
$form->prepare();

?>

<div class="row justify-content-center">
    <div class="col-sm-10 col-md-8 col-lg-5 shadow-sm">
        
        <h1 class="h2 text-center mb-3">
            <?= $this->translate('Create Account'); ?>
        </h1>

        <?= $this->form()->openTag($form); ?>

        <p class="mb-3">
            <?= sprintf($this->translate('Already have an account? %sSign in%s'), '<a href="'.$this->url('login').'">', '</a>'); ?>
        </p>

        <div class="mb-3">
            <?= $this->formLabel($form->get('username')); ?>
            <?= $this->formText($form->get('username')); ?>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('username')); ?>
            </div>
        </div>

        <div class="mb-3">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formEmail($form->get('email')); ?>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>
        </div>

        <div class="mb-3">
            <?= $this->formLabel($form->get('birthdate')); ?>
            <div class="input-group">
                <?= $this->formDateSelect($form->get('birthdate')); ?>
            </div>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('birthdate')); ?>
            </div>
        </div>

        <div class="mb-3">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formPassword($form->get('password')); ?>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('password')); ?>
            </div>
        </div>

        <div class="mb-3">
            <?= $this->formLabel($form->get('confirmPassword')); ?>
            <?= $this->formPassword($form->get('confirmPassword')); ?>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('confirmPassword')); ?>
            </div>
        </div>

        <div class="mb-3">
            <?= $this->formHidden($form->get('signupCsrf')); ?>
            <div class="invalid-feedback fw-bold">
                <?= $this->formElementErrors($form->get('signupCsrf')); ?>
            </div>
            <?= $this->formSubmit($form->get('createAccount')); ?>
        </div>

        <?= $this->form()->closeTag(); ?>

    </div>
</div>
